// FRAGMENT header written by unit u34 (reconstructed from vota_web_wasm.wasm).
//
// Voter-terminal states of the start of the election day ("início da votação": zerésima, restart, "Mais
// informações" menu) whose ProcessInput() methods were filed in unit u34. Paths inferred (directory of the
// attested relatives cquerreimprimirzeresima.cpp, creimprimindozeresima.cpp, cverificahorariozeresima.cpp).
// Split into per-class headers when merging (creiniciovotacao.h is also referenced by unit u07).
//
// These states run on the VOTER screen (api::IScreen, 640x480) and read the VOTER keyboard (api::IInputKbd,
// CPolySingletonList::instance<IInputKbd>, func 455): before the vote starts, the mesário operates the urna
// through the voter keyboard. api::CInteractiveForm<IScreen, IInputKbd>::Read() is inlined in each
// ProcessInput (cinteractiveform.h:57): current field .at(m_indice) (+72 vector, +84 index), field slot 10.
// Results: 3 = BRANCO (used as "outras opções / mais informações"), 5 = CORRIGE, 9 = CONFIRMA.
//
// WEB BUILD: none of them is reached. The simulator starts the voter thread directly in CAguardaMensagem
// (voter-training mode, unit u06), so the zerésima/restart questions and the "Mais informações" menu
// never appear in the browser.
#pragma once

#include <memory>

#include "comum/cappstate.h"
#include "vota/eleitor/comum/ctelasvota.h"      // CFormInterativoTelaVota = shared form of CTelasVota

namespace vota {

// ---------------------------------------------------------------------------------------------------------
// uenux2/src/app/vota/eleitor/iniciovotacao/creiniciovotacao.h  (path inferred by u07)
// "Reinício da votação": VOTA restarted (power loss, reboot) during the election day with votes or
// justifications already recorded; the mesário must confirm that voting continues.
// typeinfo @1546672, vtable @1546636. 20 bytes. GetInst = func 5938, StartState = 11835 (u07 fragment).
class CReinicioVotacao : public comum::CAppState {
public:
    static CReinicioVotacao& GetInst();              // wasm func 5938 (u07)
    void StartState() override;                      // wasm func 11835 (u07)
    void ProcessInput() override;                    // wasm func 11834 (this unit)
private:
    CReinicioVotacao();
    CFormInterativoTelaVota m_tela;                  // +12 (copy of CTelasVota +148, "telaReinicioVotacao")
};

// ---------------------------------------------------------------------------------------------------------
// uenux2/src/app/vota/eleitor/iniciovotacao/cconfirmaregerarzeresima.h  (path inferred)
// The zerésima of this election was generated by ANOTHER urna (EstadoGeralVota.urnaIdGerouZeresima !=
// this urna's id, e.g. the media was moved): ask whether to generate (print) it again.
// typeinfo @1546600, vtable @1546564; [2] StartState = ICF 5958 shared with CConfirmaImpressaoZeresima:
// log "Aguardando confirmação para emissão da zerésima", m_tela->Show(), stay.
// Lazy singleton @1834940, ctor inlined into CReinicioVotacao::StartState (11835): CAppState(2),
// m_tela = CTelasVota +84 ("telaConfirmaRegerarZeresima").
class CConfirmaRegerarZeresima : public comum::CAppState {
public:
    static CConfirmaRegerarZeresima& GetInst();      // inlined into 11835
    void ProcessInput() override;                    // wasm func 11838 (this unit)
private:
    CFormInterativoTelaVota m_tela;                  // +12
};

// The zerésima generator used when regenerating: CGeraZeresimaBase (ctor func 5965, u07) with vtable
// vota::CRegerarZeresima @1546500 (slot 9 "após impressão" = 11842: cut the paper). 20 bytes.
class CRegerarZeresima;                              // lazy singleton @1834912 (mutex @1834888), see 11838
class CGeraZeresima;                                 // lazy singleton @1834212 (mutex @1834188), func 5962

// ---------------------------------------------------------------------------------------------------------
// uenux2/src/app/vota/eleitor/iniciovotacao/cmaisinformacoes.h  (path inferred by u26)
// "Mais informações" menu (screen CTelasVota::CriaTelaMaisInformacoes, func 6599):
//   1 Estado da urna  2 Lista de eleitores  3 Versões de pacotes  4 Parâmetros de urna  5 Visualizar candidatos
// typeinfo @1545348, vtable @1545312. 24 bytes. GetInst(retorno) = func 1280 (u26 fragment).
class CMaisInformacoes : public comum::CAppState {
public:
    // Creates the singleton on first use (CAppState(2), m_form empty, m_retorno null); a non-null
    // `retorno` becomes the state to return to on CORRIGE. The five sub-states come back with nullptr.
    static CMaisInformacoes& GetInst(comum::CAppState* retorno = nullptr);   // wasm func 1280 (u26)
    void StartState() override;       // wasm func 11897 (u39): m_form = CTelasVota::CriaTelaMaisInformacoes();
                                      //   m_form->Show(); m_proximoEstado = this
    void ProcessInput() override;     // wasm func 11896 (this unit)
private:
    CMaisInformacoes();
    CFormInterativoTelaVota m_form;   // +12 (+16 ctrl), rebuilt by every StartState
    comum::CAppState* m_retorno = nullptr;           // +20
};

}  // namespace vota
