// uenux2/src/app/comum/relatorios/ccalculacv.cpp
// Reconstructed from vota_web_wasm.wasm (unit u25). srclocs: :58, :65, :74 (constructor, inlined in
// wasm 12110) and :109 (IncluiString, wasm 942 and inlined at the head of wasm 5967).
// Functions of this unit: 942, 5967 (free function IncluiFinal). Calcula (3700) is also written in ccalculacv.u13.cpp; Reinicia (5615)
// and the destructor (5614) were analysed by other units; they are repeated here so the file is complete.
// The algorithm was validated end to end (51/51 random cases, real BUs) in docs/bu/codigo-verificador.md.
// Not executed in the recorded votes (the BU is never generated by the web page).

#include "comum/relatorios/ccalculacv.h"

#include <format>

#include "comum/cpath.h"
#include "comum/dados/ccargos.h"
#include "comum/dados/cconfiguracaoeleicao.h"
#include "comum/relatorios/relatoriosdefs.h"
#include "comum/util/util.h"                                  // util::LeChave (util.cpp:37)
#include "ecourna/api/security/csiphashmac.hpp"
#include "ecourna/api/util/cstringutils.hpp"

namespace comum {

// Inlined into wasm 12110 (srclocs :58, :65, :74).
CCalculaCV::CCalculaCV(const std::string& identificacao, const std::string& primeiroCV, char tipo,
                       std::size_t tamanhoChave)
    : m_identificacao(identificacao)
    , m_tipo(tipo)
{
    if (identificacao.size() < 13 || identificacao.find_first_not_of("0123456789sodtSODT") != std::string::npos)
        throw CRelatoriosError(EUeComumRelatoriosError{9051},
                               "Identificação inválida [" + identificacao + "]");                    // :58
    if (primeiroCV.empty() || primeiroCV.find_first_not_of("0123456789") != std::string::npos)
        throw CRelatoriosError(EUeComumRelatoriosError{9052},
                               "Primeiro código verificador inválido [" + primeiroCV + "]");        // :65

    const std::vector<uebyte> chave = util::LeChave(CPath("/dsk/fi/estatico/chave/") / "cv.ber.pri");
    if (chave.size() < tamanhoChave)
        throw CRelatoriosError(EUeComumRelatoriosError{9053},
                               std::format("Chave privada com tamanho pequeno. Esperado pelo menos [{}]. "
                                           "Encontrado [{}]", tamanhoChave, chave.size()));           // :74
    m_chave.assign(chave.begin(), chave.begin() + tamanhoChave);
    Reinicia(primeiroCV);
}

// wasm 5614
CCalculaCV::~CCalculaCV() = default;

// wasm func 5615 (tools: ecourna_f5615). The buffer restarts from tipo + identificação + cv; the counter
// is NOT reset, so every later CV depends on all previous ones.
void CCalculaCV::Reinicia(const std::string& cv)
{
    m_dados.assign(1, m_tipo);
    m_dados += m_identificacao;
    m_dados += cv;
    m_ultimoCV = cv;
}

// wasm func 942 (srcloc :109). Called by every BU block printer before its CV data source runs.
void CCalculaCV::IncluiString(const std::string& texto)
{
    if (texto.empty())
        throw CRelatoriosError(EUeComumRelatoriosError{9054}, "String vazia");                         // :109
    m_dados += texto;
}

// wasm func 5967 (tools: comum::CCalculaCV::IncluiString@5967, because IncluiString is inlined first).
// wasm signature (i32 cargos, i32 calculadora): a free function (or a static of some other class), NOT a
// CCalculaCV member (a member would take `this` first). Called for every CV computed while the CCargos cursor
// is on the LAST cargo printed (CodVerificador / TrailerProporcionalPartido test "CCargos index + 1 == number
// of cargos"): the previous 64-bit value, the pleito date and the code of every cargo, in print order.
//                                                                              name and home file inferred
void IncluiFinal(const CCargos& cargos, CCalculaCV& calculadora)
{
    calculadora.IncluiString(calculadora.GetUltimoCV());                         // inlined 942 on +40
    const md::CPleito pleito = CConfiguracaoEleicao::GetInst().GetPleito();     // full copy (func 1281)
    calculadora.IncluiString(pleito.GetData().Format("YYYYMMDD"));               // func 706
    const auto lista = cargos.GetCargosOrdenados();       // copy of CCargos +16..+20 (8-byte SCargoEleicao)
    for (const auto& item : lista)
        calculadora.IncluiString(std::to_string(item.cargo));                    // ecourna_f296, byte +4
}

// wasm func 3700 (tools: ecourna::api::security::IMacAlgorithm::Mac, which it inlines).
std::string CCalculaCV::Calcula()
{
    m_dados += std::to_string(++m_contador);
    const std::vector<uebyte> dados(m_dados.begin(), m_dados.end());
    std::vector<uebyte> tag;
    ecourna::api::security::CSiphashMac().Mac(dados, tag, m_chave);   // SipHash-4-6, 8-byte tag (func 9498)
    std::string hexa;
    for (const uebyte byte : tag)
        hexa += std::format("{:02x}", byte);
    const ueqword valor = ecourna::api::util::CStringUtils::HexToQWord(hexa);   // tag read big-endian
    Reinicia(std::to_string(valor));
    return std::format("{:010}", valor % 10000000000ULL);
}

} // namespace comum
