// uenux2/src/app/comum/relatorios/crelutil.cpp
// Reconstructed from vota_web_wasm.wasm (unit u25).
//
// srcloc records of this file (ground truth for names/lines):
//   :58   std::string comum::(anonymous namespace)::TituloPartido()                 wasm 11181
//   :69   static std::string CRelUtil::GetIDCargaFormatado(const std::string&)      wasm 2786
//   :307  static void CRelUtil::IncluiCabecalhoEleicoesMZS(CPaperFormBuilder&, const std::string&,
//             TMunicipioID, TZonaID, TSecaoID, const std::string&, ETipoCabecalho, bool)   wasm 1543
//   :412  static std::string CRelUtil::DSCodigoVerificador()                          wasm 11182
//   :554  static std::string CRelUtil::GetSeparadorFase(const EUrnaFase)             wasm 1919
// Nothing in this file ran during the recorded votes: the web page never reaches a printed report.
//
// Rendered output of this code, obtained by running the real wasm through the patched operator flow
// (samples/bu-real/run-full/reports/bu.txt, docs/bu/codepath.md §8):
//
//     Justiça Eleitoral                      <- IncluiTitulos(cabecalho of the -pu.dat)   (func 3689)
//     Tribunal Regional Eleitoral [AC]
//                                            <- AddNewLine(1)
//     Boletim de Urna                        <- titulo
//
//     Treinamento Eleições Municipais        <- CConfiguracaoEleicao +8 (processo eleitoral)
//     1º Turno                               <- pleito.nome
//     (04/10/2026)                           <- pleito.data "(DD/MM/YYYY)"
//
//     Município                        00001 <- "{:<32s} {:05}"  TraduzLabel("<MLSN>")
//     Minha Cidade                           <- nomeMunicipio (centred)
//
//     Zona Eleitoral                    0001 <- "{:<33s} {:04}"  TraduzLabel("<ZLSN>")
//     Local de Votação                  1011 <- ETipoCabecalho::SECAO, not for eleições comunitárias
//     Seção Eleitoral                   0001 <- TraduzLabel("<SLSN>")

#include "comum/relatorios/crelutil.h"

#include <algorithm>
#include <format>
#include <string>
#include <vector>

#include "api/pattern/cpolysingleton.h"
#include "api/pattern/cpolysingletonlist.h"
#include "api/util/cdate.h"
#include "comum/cappinfo.h"
#include "comum/dados/cconfiguracaoeleicao.h"
#include "comum/dados/clocal.h"
#include "comum/dados/cpartidos.h"
#include "comum/dados/cpe.h"
#include "comum/dados/md/ctradutorfrase.h"
#include "comum/informacao/cinformacaoeleicao.h"
#include "comum/relatorios/ccalculacv.h"
#include "comum/relatorios/csubstituidortitulo.h"

namespace comum {

namespace {

// wasm func 11181 (srcloc :58), table slot 3050: data source (std::string(*)()) of the party title of a
// BU / zerésima block, e.g. "Partido: 91 - PEsp". The party is the CURRENT entry of the CPartidos
// CDataMap (the report generator iterates it and prints the form, which calls this function).
std::string TituloPartido()
{
    const auto& partidos = CPartidos::GetInst();                                 // ecourna_f819
    if (partidos.IsEnd())                                                        // m_atual == end()
        throw CRelatoriosError(EUeComumRelatoriosError{9084}, "Partido não posicionado");   // :58
    const md::CPartido& partido = partidos.GetCurrent();                         // func 1283
    return md::CTradutorFrase::TraduzLabel("<PLSN>") + ": " + std::to_string(partido.GetNumero()) + " - "
           + partido.GetSigla();                                                 // +0 u16, +4 string
}

// Order in which the eleições are listed in the header: CSituacoesEleicoes::ordemImpressao (byte +5 of the
// 8-byte record {TEleicaoID id; uebyte ordemAquisicao; uebyte ordemImpressao}).
// NOTE: the lambda takes both md::CEleicaoPE BY VALUE, so every comparison deep-copies two eleições
// (name + vector<CCargo> of 140-byte cargos with their optional details + vector<int>). This is why the
// std::sort instantiation below is ~120 KB of wasm.
const auto PorOrdemImpressao = [](md::CEleicaoPE a, md::CEleicaoPE b) {
    const auto& cfg = CConfiguracaoEleicao::GetInst();
    return cfg.GetSituacoesEleicoes(a.GetId()).GetOrdemImpressao()                  // func 271 -> CPleito::
           < cfg.GetSituacoesEleicoes(b.GetId()).GetOrdemImpressao();              //   GetSituacoesEleicoes
};
// Template instances generated by std::sort(eleicoes, PorOrdemImpressao) (libc++, _ClassicAlgPolicy,
// md::CEleicaoPE* iterators, 52-byte elements; the empty comparator was removed by dead-argument elim.):
//   wasm 5582  std::__introsort<..., false>(first, last, depth, leftmost)   96,893 bytes (recursive)
//   wasm 5577  std::__insertion_sort_incomplete(first, last) -> bool
//   wasm 1386  std::__sort3(x, y, z)          wasm 3687  std::__sort4(x1..x4)
//   wasm 5578  std::__sort5(x1..x5)
//   wasm 818   std::swap(md::CEleicaoPE&, md::CEleicaoPE&)     (move-construct tmp + 2 move-assigns)
//   wasm 817   md::CEleicaoPE::operator=(md::CEleicaoPE&&)      (implicit)
//   wasm 271   CConfiguracaoEleicao::GetSituacoesEleicoes(TEleicaoID) const = GetPleito() (+28)
//              .GetSituacoesEleicoes(id)   (inline accessor; also used by CCargos' comparators 11558/11559)

} // namespace

// ------------------------------------------------------------------------------------------------------
// wasm func 1543 (srcloc :307). Callers: vota::CGeraBU::StartState (12110, BU), CGeraRelatorios (12105,
// BUJ/BIM/BEHB), CImpressaoPU (11902), CImpressaoListaEleitores (11908), vota_f5977 (zerésima / resumo),
// CGeradorRelVersaoPacoteDados (11223).
void CRelUtil::IncluiCabecalhoEleicoesMZS(api::CPaperFormBuilder& b, const std::string& titulo,
                                          const TMunicipioID municipio, const TZonaID zona,
                                          const TSecaoID secao, const std::string& nomeMunicipio,
                                          const ETipoCabecalho tipo, const bool usaPleitoContingencia)
{
    md::CPleito pleito = CConfiguracaoEleicao::GetInst().GetPleito();            // copy (func 1281), cfg +28

    // A contingency urna carries the data of both rounds: from the date of the 2nd round on, its reports
    // are headed with pleito 2.
    if (usaPleitoContingencia && tipo == ETipoCabecalho::CONTINGENCIA) {
        if (!CPE::Existe()) {                                                    // func 2788 (@1839112)
            CAppInfo::GetInst();                                                 // func 185 (result unused)
            CPE::CreateInst(CarregaProcessoEleitoral());                         // shared_f2273 + 2787
        }
        if (CPE::GetInst().TemPleito2()) {                                       // byte +156
            const api::CDate hoje;                                               // func 1382 (today)
            const md::CPleito& pleito2 = CPE::GetInst().GetPleito2();            // func 1267
            if (pleito2.GetData() == hoje || pleito2.GetData() < hoje)           // 4 x u16 ==, then <=> (1261)
                pleito = pleito2;                                                // CPleito::operator= (5597)
        }
    }

    const auto& cfg = CConfiguracaoEleicao::GetInst();
    IncluiAvisoModoDemonstracao(b);                                              // func 5583
    CSubstituidorTitulo::IncluiTitulos(b, cfg.GetParametros().GetCabecalho(),   // func 3689, cfg +188
                                       CLocal::GetInst().GetUF());               // func 1702
    b.AddNewLine(1);
    if (!titulo.empty()) {
        b.AddText(titulo, 1, 2);
        b.AddNewLine(1);
    }
    if (cfg.GetOrigem() == md::EOrigemConfiguracao::COMUNITARIA) {               // cfg +20 == 2
        b.AddText("Eleições Comunitárias", 1, 2);
        b.AddNewLine(1);
    }
    b.AddText(cfg.GetNomeProcessoEleitoral(), 1, 2);                             // cfg +8
    b.AddText(pleito.GetNome(), 1, 2);                                           // +4
    b.AddText(pleito.GetData().Format("(DD/MM/YYYY)"), 1, 2);                    // +16, func 706
    b.AddNewLine(1);

    {
        std::vector<md::CEleicaoPE> eleicoes = pleito.GetEleicoes();             // +24, copy (func 1953)
        if (eleicoes.size() >= 2) {
            std::sort(eleicoes.begin(), eleicoes.end(), PorOrdemImpressao);      // func 5582
            for (const auto& eleicao : eleicoes)
                b.AddText(eleicao.GetNome(), 1, 2);                              // CEleicaoPE +12
            b.AddNewLine(1);
        }
    }                                                                            // ~CEleicaoPE = func 730

    const CLocal& local = CLocal::GetInst();                                     // func 401
    const auto& configuracao = CConfiguracaoEleicao::GetInst();
    b.AddText(std::format("{:<32s} {:05}", md::CTradutorFrase::TraduzLabel("<MLSN>"), municipio), 1, 0);
    b.AddText(nomeMunicipio, 1, 2);
    b.AddNewLine(1);
    b.AddText(std::format("{:<33s} {:04}", md::CTradutorFrase::TraduzLabel("<ZLSN>"), zona), 1, 0);

    switch (tipo) {
    case ETipoCabecalho::SECAO:
        if (configuracao.GetOrigem() != md::EOrigemConfiguracao::COMUNITARIA)
            b.AddText(std::format("{:<33s} {:04}", std::string_view("Local de Votação"),
                                  local.GetLocalID()), 1, 0);                    // func 1933
        b.AddText(std::format("{:<33s} {:04}", md::CTradutorFrase::TraduzLabel("<SLSN>"), secao), 1, 0);
        if (local.GetQtdAgregadas() != 0) {                                      // func 2816
            // The label is translated first and turned into a runtime format string.
            const std::string formato = std::format(
                "{:<33s} {{:04}}", md::CTradutorFrase::TraduzLabel("Quantidade de <SCPB> agregad<S|os|os|as>"));
            const int qtd = local.GetQtdAgregadas();                             // inlined: VerificaLido(
                                                                                 //  "GetQtdAgregadas"), size & 255
            b.AddText(std::vformat(formato, std::make_format_args(qtd)), 1, 0);
            b.AddText(FormataSecoesAgregadas(
                          md::CTradutorFrase::TraduzLabel("<SCPN> agregad<S|os|os|as>: {}")), 1, 2);   // 5738
        }
        break;

    case ETipoCabecalho::MESA_RECEPTORA:                                         // seção = mesa * 10 + urna
        b.AddText(std::format("{:<34s} {:03}", std::string_view("Mesa Receptora"), secao / 10), 1, 0);
        b.AddText(std::format("{:<34s}   {}", std::string_view("Urna"), secao % 10), 1, 0);
        break;

    case ETipoCabecalho::CONTINGENCIA:
        b.AddText("Urna de contingência", 1, 2);
        break;

    case ETipoCabecalho::INVALIDO:                                               // the binary throws for 3 only;
        throw CRelatoriosError(EUeComumRelatoriosError{9086},                   // values > 3 print nothing
                               std::format("Tipo inválido: {}", tipo));          // :307
    }
    b.AddNewLine(1);
}

// ------------------------------------------------------------------------------------------------------
// wasm func 2786 (srcloc :69). "123456789012345678901234" -> "123.456.789.012.345.678.901.234".
// Callers: CGeradorBU::ImprimePreTexto (11256, histórico de cargas), the BU trailer (12110), the
// zerésima trailer (5579), CGeraRelatorios (12105).
std::string CRelUtil::GetIDCargaFormatado(const std::string& idCarga)
{
    if (idCarga.size() <= 20)
        throw CRelatoriosError(EUeComumRelatoriosError{9085}, "ID de carga inválido: [" + idCarga + "]");   // :69
    return idCarga.substr(0, 3) + "." + idCarga.substr(3, 3) + "." + idCarga.substr(6, 3) + "."
           + idCarga.substr(9, 3) + "." + idCarga.substr(12, 3) + "." + idCarga.substr(15, 3) + "."
           + idCarga.substr(18, 3) + "." + idCarga.substr(21);
}

// ------------------------------------------------------------------------------------------------------
// wasm func 11182 (srcloc :412), table slot 3048: data source of the "Código Verificador" printed under
// the "Histórico de código de carga" of the BU (see docs/bu/codigo-verificador.md). The CCalculaCV
// instance is the one CGeraBU publishes in api::CPolySingletonList while the BU is generated.
std::string CRelUtil::DSCodigoVerificador()
{
    auto& calculadora = api::CPolySingleton<CCalculaCV>::instance();             // func 1282, :412
    const std::string cv = calculadora.Calcula();                                // func 3700 (10 digits)
    return std::format("Código Verificador: {}.{}.{}.{}", cv.substr(0, 1), cv.substr(1, 3), cv.substr(4, 3),
                       cv.substr(7, 3));
}

// ------------------------------------------------------------------------------------------------------
// wasm func 1919 (srcloc :554). The 38-column separator that frames every block of a report.
// EUrnaFase is a char enum: '1' oficial, '2' simulado, '3' treinamento (CEstadoGeral +48).
// (The comment in cgerabu.cpp (unit u08) swaps '1' and '2'; the br_table here is: '1' plain,
//  '2' SIMULADO, '3' TREINAMENTO.)
std::string CRelUtil::GetSeparadorFase(const EUrnaFase fase)
{
    if (CInformacaoEleicao(CConfiguracaoEleicao::GetInst()).EhModoDemonstracao())        // funcs 603, 2286
        return "============DEMONSTRAÇÃO==============";

    switch (fase) {
    case EUrnaFase::OFICIAL:     return "======================================";
    case EUrnaFase::SIMULADO:    return "===============SIMULADO===============";
    case EUrnaFase::TREINAMENTO: return "==============TREINAMENTO=============";
    default:
        throw CRelatoriosError(EUeComumRelatoriosError{9087}, std::format("Fase inválida: {}", fase));   // :554
    }
}

// ------------------------------------------------------------------------------------------------------
// wasm func 1942, table slot 1567 (tools: comum_f1942). Data source of the BU / zerésima / PU header line
// with the urna's internal number (the carga's "número interno da urna"). name inferred (the sibling
// data source DSCodigoVerificador is a CRelUtil static; unit u09 calls it DS_CodigoIdentificacaoUE)
std::string CRelUtil::DSCodigoIdentificacaoUE()
{
    const auto& estadoGeral = CAppInfo::GetInst().GetGeral();                    // inlined 185 + func 291
    return std::format("Código identificação UE       {:08}",
                       estadoGeral.GetCorrespondencia().GetNumeroInternoUrna());   // CEstadoGeral +60
}

// ------------------------------------------------------------------------------------------------------
// wasm func 5583 (tools: comum_f5583). First lines of every report printed in demonstration mode.
// Callers: IncluiCabecalhoEleicoesMZS (1543) and vota_f5591. name inferred
void CRelUtil::IncluiAvisoModoDemonstracao(api::CPaperFormBuilder& b)
{
    if (CInformacaoEleicao(CConfiguracaoEleicao::GetInst()).EhModoDemonstracao()) {       // funcs 603, 2286
        b.AddText("IMPRESSO EM MODO DEMONSTRAÇÃO", 1, 2);
        b.AddNewLine(2);
    }
}

// ------------------------------------------------------------------------------------------------------
// wasm func 5738 (tools: comum_f5738). `formato` is an already translated label with one "{}" (e.g.
// "Seções agregadas: {}"); the placeholder receives the aggregated sections as "0012 0034 0056".
// Callers: IncluiCabecalhoEleicoesMZS (1543), CRelatorioTesteImpressora::GetLinhasLocal (11188).
// name inferred
std::string CRelUtil::FormataSecoesAgregadas(const std::string& formato)
{
    const CLocal& local = CLocal::GetInst();                                     // inlined func 401
    std::string lista;
    const uebyte qtd = local.GetQtdAgregadas();         // inlined: VerificaLido("GetQtdAgregadas");
                                                        // secao present ? (agregadas.size() & 0xFF) : 0
    if (qtd != 0) {
        const std::vector<TSecaoID> agregadas = local.GetAgregadas();            // func 3752
        lista += std::format("{}{:04}", "", agregadas[0]);
        for (uebyte i = 1; i < qtd; ++i)
            lista += std::format("{}{:04}", " ", agregadas[i]);
    }
    return std::vformat(formato, std::make_format_args(lista));
}

} // namespace comum
