// Reconstructed from vota_web_wasm.wasm (unit u09).
// Original: uenux2/src/app/vota/eleitor/fimvotacao/cimprimindobim.h (path inferred from cimprimindobim.cpp,
// attested by srcloc lines 50, 51, 66).
//
// "Imprimindo BIM" = prints the Boletim de Identificação de Mesários (trab/bim.dat, generated by
// CGeraRelatorios), "via única". Reached when CInformacaoEleicao::IdentificaMesarios().
//
// RTTI: comum::CAppState <- vota::CImprimindoBim (typeinfo @1541624, vtable @1541540)
//   [0] 174 [1] 144 [2] StartState 12071 (ImprimeRelatorio inlined) [3..8] defaults
#pragma once

#include "comum/cappstate.h"

namespace vota {

class CImprimindoBim final : public comum::CAppState {
public:
    /// Lazy singleton, wasm func 5985 (unit u37): vota_f764(@1833684, @1833708, vtable, flags 0).
    static CImprimindoBim& GetInst();

    void StartState() override;       // wasm func 12071 (srcloc 50, 51)

private:
    void ImprimeRelatorio();          // srcloc :66, inlined into StartState
};

}  // namespace vota
