// FRAGMENT reconstructed by unit u07 from vota_web_wasm.wasm.
// Original file (path inferred): uenux2/src/app/vota/eleitor/iniciovotacao/testeteclado/cretomada.cpp
// vota::testeteclado::CRetomada : testeteclado::CBase : CEstadoComDesligamentoAutomatico (typeinfo @1546760,
// vtable @1546708). "Retomada" = resuming after a restart: the keyboard-test screen shown before
// CReinicioVotacao. testeteclado::CBase adds three pure virtuals:
//   [10] CriaTela (11831)  [11] GetEstadoPassouNoTeste (11830; name attested by CPreZeresima::GetEstadoPassouNoTeste)
//   [12] GetEstadoSemTeste (11829; used when the mesário chooses "Não testar")
// CRetomada +36: bool m_podePularTeste, set by CriaTela (the zerésima was generated by this urna, or the
// keyboard was already tested after conversion -> screen "Quer testar o teclado?" with "Não testar").
#include "vota/eleitor/iniciovotacao/testeteclado/cretomada.h"

#include "vota/eleitor/iniciovotacao/creiniciovotacao.h"

namespace vota::testeteclado {

// wasm func 11829 (vtable slot 12)                                                   // name inferred
comum::CAppState* CRetomada::GetEstadoSemTeste()
{
    // Skipping the test is only possible when CriaTela offered it; otherwise stay (the base class logs
    // "Teste de Teclado do TE não executado" only when the returned state differs from this).
    return m_podePularTeste ? &CReinicioVotacao::GetInst() : this;              // func 5938
}

} // namespace vota::testeteclado
