// Reconstructed from vota_web_wasm.wasm (unit u04). Original: uenux2/src/app/comum/dados/celeitores.cpp
//
// See ccargos.cpp for the error types (CErroDados / CErroPattern).
//
// Not in this file (inlined elsewhere): StaticLoad (lines 395/407 -> 7787), MarcaVotou (456/460 ->
// vota::CSincronismoOperador::vf2, 10210), GetCurrentAbrangenciaEleitor (497 -> CEleitorVotando::
// IniciaCiclo, 7377). Template instantiations generated by this file (std::sort helpers for
// vector<md::CEleitorDinamico>, tree destructors...) are listed at the end.
#include "celeitores.h"

#include <algorithm>
#include <filesystem>
#include <format>

#include "cconfiguracaoeleicao.h"
#include "dao/celeitordinamicodao.h"
#include "md/eleitor/celeitordadoshabilitacao.h"
#include "md/eleitor/cimpedido.h"
#include "../appinfo/cappinfo.h"          // GetEstado<...>

namespace comum {

using CErroDados   = ecourna::api::exception::CBaseError<EUeComumDadosError>;
using CErroPattern = ecourna::api::exception::CBaseError<ecourna::api::pattern::EPatternErr>;

std::mutex  CEleitores::s_mutex;
CEleitores* CEleitores::s_inst = nullptr;

namespace {

// wasm func 3721 - name inferred. Body of CEleitores::GetCurrentAbrangenciaEleitor (line 497, whose
// srcloc sits in 7377) once the current voter is known; also used by GetQtdAptos, DynamicCreate and
// the voter-state machine. Decides which cargos a voter may vote for in THIS urna:
//   no temporary transfer (decorator +48 == 0), or domicile município == urna município -> MUNICIPAL
//   same UF (decorator +52) as the urna                                                 -> ESTADUAL
//   otherwise                                                                           -> FEDERAL
md::ETipoAbrangencia GetAbrangenciaEleitor(const CEleitorDetalhe& detalhe, const std::string& uf,
                                           TMunicipioID municipio)
{
    const md::CEleitorDecorator& e = detalhe.GetEleitor();
    if (e.GetTipoTransferenciaTemporaria() == 0 || e.GetMunicipioDomicilio() == municipio)
        return md::ETipoAbrangencia::MUNICIPAL;
    return e.GetUFDomicilio() == uf ? md::ETipoAbrangencia::ESTADUAL : md::ETipoAbrangencia::FEDERAL;
}

// Comparators passed as function pointers to std::sort in CompleteLoad
//   wasm 11532 (table slot 2386): md::CImpedido by identity (+4 string, then +16 tipo)
//   wasm 11531 (table slot 2387): md::CEleitorDinamico by identity (+0 string, then +12 tipo)
bool ComparaImpedido(const md::CImpedido& a, const md::CImpedido& b) { return a.GetIdentidade() < b.GetIdentidade(); }
bool ComparaDinamico(const md::CEleitorDinamico& a, const md::CEleitorDinamico& b) { return a.GetTitulo() < b.GetTitulo(); }

}  // namespace

// wasm func 326 (srcloc line 44)
CEleitores& CEleitores::GetInst()
{
    std::lock_guard lock(s_mutex);
    if (s_inst == nullptr)
        throw CErroPattern(ecourna::api::pattern::EPatternErr{1303}, "CEleitores - instancia nao criada");
    return *s_inst;
}

// wasm func 2824 - IDataSourceAptos slot 0 (name inferred). Used by the BU QR code (APTA/APTS/APTT),
// by CDataSourcesRelatorio::GetLinhasEleitoresAptos (BU/zerésima "eleitores aptos" line) and by
// vota::CGravaResultado. Counts every voter who may vote in the current round, once for his own
// abrangência and once for each wider one (a MUNICIPAL voter also counts for ESTADUAL and FEDERAL).
std::map<md::ETipoAbrangencia, SQtdeAptos> CEleitores::GetQtdAptos() const
{
    std::map<md::ETipoAbrangencia, SQtdeAptos> qtd;
    for (const auto abr : std::vector{md::ETipoAbrangencia::MUNICIPAL, md::ETipoAbrangencia::ESTADUAL,
                                      md::ETipoAbrangencia::FEDERAL})
        qtd[abr] = SQtdeAptos{};

    for (const auto& [identidade, detalhe] : GetContainer()) {
        if (!detalhe.PodeVotar())                                   // comum_f2266: impedimento do turno
            continue;
        const md::ETipoAbrangencia abr = GetAbrangenciaEleitor(detalhe, m_uf, m_municipio);
        if (abr > md::ETipoAbrangencia::FEDERAL)
            continue;
        std::vector<md::ETipoAbrangencia> abrangencias;
        for (auto a = abr;; a = md::ETipoAbrangencia(int(a) + 1)) {
            abrangencias.push_back(a);
            if (a == md::ETipoAbrangencia::FEDERAL)
                break;
        }
        const bool tte = detalhe.GetEleitor().GetTipoTransferenciaTemporaria() != 0;
        for (const auto a : abrangencias) {
            if (!tte)
                ++qtd[a].qtdAptosSecao;
            else
                ++qtd[a].qtdAptosTTE;
        }
    }
    return qtd;
}

// wasm func 2825 (srcloc lines 435, 439, 447)
void CEleitores::MarcaEleitorFoiHabilitado(const CEleitorDadosHabilitacao& dados)
{
    CEleitorDetalhe* detalhe = GetCurrent();                         // CDataMap::GetCurrent (656)
    if (detalhe == nullptr)
        throw CErroDados(EUeComumDadosError{7842}, "Item inexistente");
    if (!detalhe->TemDinamico())
        throw CErroDados(EUeComumDadosError{7843}, "Dados dinâmicos não carregados");
    if (detalhe->GetDinamico().GetEstadoComparecimento() == md::EEstadoComparecimento::VOTOU)
        throw CErroDados(EUeComumDadosError{7844}, "Eleitor já votou");

    detalhe->MarcaHabilitado(dados);        // CEleitorDetalhe::MarcaHabilitado, inlined (celeitordetalhe.cpp)
}

// wasm func 5761 (srcloc lines 301, 305, 358). Only caller: the "gera dados dinâmicos" step
// (6737 = vota::CInformacaoEleitor::GerarDadosDinamicos per u02, called by votaInit and
// vota::CGeraDadosDinamicos::StartState), once for the uenux.db of each flash, both in the CURRENT
// round's work directory: CPath::GetPathTrab(interna, turno)/uenux.db (shared_f2826 -> /dsk/fi/...)
// then GetPathTrab(externa, turno)/uenux.db (api_f5762 -> /dsk/fe/...). Skipped when fase == '3' and
// the urna is in "treinamento do eleitor" mode (comum_f697) - the case of the web simulator.
void CEleitores::DynamicCreate(const std::string& arquivoBanco) const
{
    if (GetContainer().empty())
        throw CErroDados(EUeComumDadosError{7837}, "Não há informações carregadas");
    if (GetContainer().begin()->second.TemDinamico())
        throw CErroDados(EUeComumDadosError{7838}, "Informações dinâmicas já carregadas");

    // Which abrangências have at least one cargo in this urna (linear std::find over the set).
    bool temMunicipal = false, temEstadual = false, temFederal = false;
    if (!m_abrangenciasCargos.empty()) {
        temMunicipal = std::ranges::find(m_abrangenciasCargos, md::ETipoAbrangencia::MUNICIPAL) != m_abrangenciasCargos.end();
        temEstadual  = std::ranges::find(m_abrangenciasCargos, md::ETipoAbrangencia::ESTADUAL)  != m_abrangenciasCargos.end();
        temFederal   = std::ranges::find(m_abrangenciasCargos, md::ETipoAbrangencia::FEDERAL)   != m_abrangenciasCargos.end();
    }

    std::vector<md::CEleitorDinamico> novos;
    for (const auto& [chave, detalhe] : GetContainer()) {
        const md::CEleitorIdentidade id =
            detalhe.GetEleitor().GetIdentidadePorTipo(detalhe.GetEleitor().GetTipoIdentificadorPrincipal());
        bool temCargo = false;
        switch (GetAbrangenciaEleitor(detalhe, m_uf, m_municipio)) {
        case md::ETipoAbrangencia::MUNICIPAL: temCargo = temMunicipal || temEstadual || temFederal; break;
        case md::ETipoAbrangencia::ESTADUAL:  temCargo = temEstadual || temFederal; break;
        case md::ETipoAbrangencia::FEDERAL:   temCargo = temFederal; break;
        default:                              temCargo = false; break;
        }
        // md::CEleitorDinamico(titulo, identidadeHabilitacao, estado) - wasm 2800
        novos.emplace_back(id, id, temCargo ? md::EEstadoComparecimento::FALTOU
                                            : md::EEstadoComparecimento::SEM_CARGO_PARA_VOTAR);
    }

    dao::CEleitorDinamicoDAO dao(arquivoBanco);              // creates table eleitor_dinamico if needed
    std::vector<md::CEleitorDinamico> existentes = dao.SelectAll();   // vtable slot 8 (3766)
    if (existentes.empty()) {
        dao.GetConexao().BeginTransaction();                 // connection vtable slot 2      // ?
        for (const auto& d : novos)
            dao.Insert(d);                                   // vtable slot 3 (5776)
        dao.GetConexao().Commit();                           // connection vtable slot 3      // ?
    } else {
        // Re-running over an existing database is accepted only if it holds exactly the same rows.
        std::sort(existentes.begin(), existentes.end());     // operator< = by titulo (wasm 3762 ...)
        std::sort(novos.begin(), novos.end());
        if (existentes != novos)                             // md::CEleitorDinamico::operator== (inlined)
            throw CErroDados(EUeComumDadosError{7839},
                             std::format("Já existem informações dinâmicas no banco {}", arquivoBanco));
    }
}

// wasm func 6734 (srcloc lines 205, 219, 238). In the binary this body is inlined into a wrapper
// (vota::CInformacaoEleitor::CarregarDadosDinamicos, u02's name) that also loads rdv.dat, the
// justificativas and the mesários (see u04-foreign-fragments.cpp); the wrapper runs it only when
// CEstadoGeralVota.treinamentoEleitor (+72) is false. Arguments: CPath::Estatico() and
// GetPathTrab(interna, turno)/uenux.db (shared_f2826).
void CEleitores::CompleteLoad(const std::string& dirEstatico, const std::string& arquivoBanco)
{
    if (!std::filesystem::exists(arquivoBanco))                                   // api_f412
        throw CErroDados(EUeComumDadosError{7834}, std::format("Não existe o arquivo {}", arquivoBanco));

    std::vector<std::string> arquivosImpedidos;                                   // api_f1936
    for (const auto& nome : m_arquivosImpedidos)
        arquivosImpedidos.push_back(dirEstatico + nome);
    std::vector<md::CImpedido> impedidos = GetEleitoresImpedidos(arquivosImpedidos);   // api_f5767
    std::vector<md::CEleitorDecorator> eleitores = GetEleitoresEstaticos(dirEstatico);  // api_f5772
    std::vector<md::CEleitorDinamico> dinamicos;
    {
        dao::CEleitorDinamicoDAO dao(arquivoBanco);
        dinamicos = dao.SelectAll();                                              // vtable slot 8
    }
    std::sort(impedidos.begin(), impedidos.end(), ComparaImpedido);               // 3765
    std::sort(dinamicos.begin(), dinamicos.end(), ComparaDinamico);               // 5766

    // Static roll and SQLite rows must describe the same voters, in the same (sorted) order.
    // (Note: the static roll is NOT sorted here; GetEleitoresEstaticos returns it sorted.)   // ?
    auto divergencia = [] {
        return CErroDados(EUeComumDadosError{7835}, "Havia divergência entre os títulos dinâmicos e os estáticos");
    };
    if (eleitores.size() != dinamicos.size())
        throw divergencia();
    for (std::size_t i = 0; i < eleitores.size(); ++i) {
        const auto id = eleitores[i].GetIdentidadePorTipo(eleitores[i].GetTipoIdentificadorPrincipal());
        if (!(id == dinamicos[i].GetTitulo()))
            throw divergencia();
    }

    Container novos;
    std::map<md::CEleitorIdentidade, md::CEleitorIdentidade> identidades;
    std::size_t indiceImpedido = 0;
    std::uint32_t qtdVotaram = 0;
    for (std::size_t i = 0; i < eleitores.size(); ++i) {
        const md::CEleitorDecorator& eleitor = eleitores[i];
        ValidaIdentidadesEleitor(eleitor);
        const md::CEleitorIdentidade principal = eleitor.GetIdentidadePorTipo(eleitor.GetTipoIdentificadorPrincipal());
        const std::vector<md::CEleitorIdentidade> ids = eleitor.GetIdentificadores();   // copy
        auto [it, inserido] = novos.try_emplace(principal,
                                                LoadEleitorDetalhe(eleitor, impedidos, indiceImpedido, &dinamicos[i]));
        if (!inserido)
            throw CErroDados(EUeComumDadosError{7836},
                             std::format("Identificador principal {} duplicado", principal.GetNumero()));  // string_view arg
        const auto estado = dinamicos.at(i).GetEstadoComparecimento();
        for (const auto& id : ids)
            identidades.emplace(id, principal);                 // every identifier -> principal one
        qtdVotaram += (estado == md::EEstadoComparecimento::VOTOU);
    }

    SetContainer(std::move(novos));                             // also resets the current iterator
    m_qtdVotaram = qtdVotaram;
    m_identidadePrincipal = std::move(identidades);
    m_dinamicosCarregados = true;
}

// wasm func 5764 (srcloc celeitores.cpp:719 + inlined CEleitorDetalhe ctor celeitordetalhe.cpp:49 +
// md::CImpedido::GetImpedimentoP2 cimpedido.cpp:46). Observed executing (from StaticLoad at start-up).
// Merge-join of the (sorted) voter roll with the (sorted) impediment list: `indiceImpedido` walks
// the impediment list in step with the caller's walk over the voters.
CEleitorDetalhe CEleitores::LoadEleitorDetalhe(const md::CEleitorDecorator& eleitor,
                                               const std::vector<md::CImpedido>& impedidos,
                                               std::size_t& indiceImpedido,
                                               const md::CEleitorDinamico* dinamico) const
{
    md::ETipoImpedimento p1 = md::ETipoImpedimento::NENHUM;
    md::ETipoImpedimento p2 = md::ETipoImpedimento::NENHUM;
    if (indiceImpedido < impedidos.size()) {
        const md::CImpedido& impedido = impedidos[indiceImpedido];           // 32 bytes
        const auto id = eleitor.GetIdentidadePorTipo(eleitor.GetTipoIdentificadorPrincipal());
        if (id == impedido.GetIdentidade()) {
            ++indiceImpedido;
            p1 = impedido.GetImpedimentoP1();                                // +20
            // cimpedido.cpp:46: throws 8068 "Não há informação de 2o turno" when absent
            p2 = impedido.TemImpedimentoP2() ? impedido.GetImpedimentoP2() : md::ETipoImpedimento::NENHUM;
        } else if (id > impedido.GetIdentidade()) {
            // The current impediment is smaller than every remaining voter: it matches nobody.
            const auto& idImp = impedido.GetIdentidade();
            throw CErroDados(EUeComumDadosError{7851},
                std::format("CEleitores::LoadEleitorDetalhe - ({}-{} > {}-{}). {} com marcação de impedido "
                            "não encontrado nas listas de eleitores e de tte",
                            id.GetNumero(), id.GetTipo(), idImp.GetNumero(), idImp.GetTipo(), idImp.GetNumero()));
        }
    }
    if (dinamico == nullptr)
        return CEleitorDetalhe(eleitor, p1, p2);
    return CEleitorDetalhe(eleitor, *dinamico, p1, p2);
}

// wasm func 5765 (srcloc line 738)
void CEleitores::ValidaIdentidadesEleitor(const md::CEleitorDecorator& eleitor) const
{
    for (const auto& id : eleitor.GetIdentificadores())
        if (id.GetTipo() == m_tipoIdentificadorPrincipal)
            return;
    // format args (packed kinds 431 = handle, string_view): the enum (formatted as an integer) and
    // only the NUMBER string of the voter's principal identity.
    throw CErroDados(EUeComumDadosError{7852},
        std::format("Identificador principal ({}) ausente para o eleitor ({})", m_tipoIdentificadorPrincipal,
                    eleitor.GetIdentidadePorTipo(eleitor.GetTipoIdentificadorPrincipal()).GetNumero()));
}

// wasm func 6034 - name inferred. Called through comum_f2821 (tipo 1), comum_f1935 (tipo 2) and the
// twin comum_f2822 (tipo 0, not in u04): the BU QR-code counters HBBM / HBBG / HBSB and the BU.
std::uint16_t CEleitores::QtdVotaramPorTipoHabilitacao(md::ETipoHabilitacao tipo) const
{
    std::uint16_t qtd = 0;
    for (const auto& [id, detalhe] : GetContainer()) {
        if (!detalhe.TemDinamico())
            continue;
        if (detalhe.GetDinamico().GetTipoHabilitacao() != tipo)
            continue;
        qtd += detalhe.GetDinamico().GetEstadoComparecimento() == md::EEstadoComparecimento::VOTOU;
    }
    return qtd;
}

// ---------------------------------------------------------------------------------------------
// Text sources. Each one inlines CEleitores::GetInst() (srcloc line 44) and CDataMap::GetCurrent.
// std::vformat is used because the format string comes from the screen layout (runtime string).

// wasm func 11529 (srcloc line 756)
std::string CEleitorDadoNomeParaUrna::Text(const std::string& formato)
{
    const CEleitorDetalhe* detalhe = CEleitores::GetInst().GetCurrent();
    if (detalhe == nullptr)
        throw CErroDados(EUeComumDadosError{7854}, "Não posicionado no eleitor corretamente");
    const md::CEleitorDecorator& e = detalhe->GetEleitor();
    const std::string& nome = e.GetNomeSocial().empty() ? e.GetNome() : e.GetNomeSocial();
    const std::string nomeParaUrna = nome.substr(0, 40);
    return std::vformat(formato, std::make_format_args(nomeParaUrna));
}

// wasm func 11528 (srcloc line 772)
std::string CEleitorDadoSequencial::Text(const std::string& formato)
{
    const CEleitorDetalhe* detalhe = CEleitores::GetInst().GetCurrent();
    if (detalhe == nullptr)
        throw CErroDados(EUeComumDadosError{7855}, "Não posicionado no eleitor corretamente");
    const int sequencial = detalhe->GetEleitor().GetSequencial();              // +0
    return std::vformat(formato, std::make_format_args(sequencial));
}

// wasm func 11527 (srcloc line 784)
std::string CEleitorDadoSecao::Text(const std::string& formato)
{
    const CEleitorDetalhe* detalhe = CEleitores::GetInst().GetCurrent();
    if (detalhe == nullptr)
        throw CErroDados(EUeComumDadosError{7856}, "Não posicionado no eleitor corretamente");
    const unsigned secao = detalhe->GetEleitor().GetSecao();                   // +4 (uint16)
    return std::vformat(formato, std::make_format_args(secao));
}

// wasm func 11526 (srcloc line 796)
std::string CEleitorDadoTTE::Text()
{
    const CEleitorDetalhe* detalhe = CEleitores::GetInst().GetCurrent();
    if (detalhe == nullptr)
        throw CErroDados(EUeComumDadosError{7857}, "Não posicionado no eleitor corretamente");
    if (detalhe->GetEleitor().GetTipoTransferenciaTemporaria() == 0)
        return {};
    return "Transferência Temporária";      // stored in Latin-1 in the binary (24 bytes)
}

// ---------------------------------------------------------------------------------------------
// Template instantiations emitted in this translation unit (library code, not reconstructed):
//   282   std::swap<md::CEleitorDinamico>                       (move-construct tmp, two move-assigns)
//   470   md::CEleitorDinamico::operator=(CEleitorDinamico&&)   (implicitly defined; strings moved,
//                                                              optional<CEleitorIdentidade> handled)
//   1392  std::__sort3<_ClassicAlgPolicy, __less<>&, md::CEleitorDinamico*>
//   3757  std::__sort4<..., md::CEleitorDinamico*>
//   5749  std::__sort5<..., md::CEleitorDinamico*>
//   5748  std::__insertion_sort_incomplete<..., md::CEleitorDinamico*>
//   3762  std::__introsort<..., md::CEleitorDinamico*>          (std::sort in DynamicCreate)
//   5766  std::__introsort<_ClassicAlgPolicy, bool(*&)(const CEleitorDinamico&, const CEleitorDinamico&),
//         md::CEleitorDinamico*>                               (std::sort in CompleteLoad, ComparaDinamico)
//   5751  std::__insertion_sort_incomplete<..., fn-ptr compare, md::CEleitorDinamico*>
//   2820  std::__sort4<..., fn-ptr compare, md::CEleitorDinamico*>
//   3758  std::__split_buffer<md::CEleitorDinamico>::~__split_buffer   (vector growth)
//   3759  std::__uninitialized_allocator_relocate<md::CEleitorDinamico> (vector growth)
//   3763  std::vector<md::CEleitorDinamico>::__destroy_vector::operator()
//   2800  md::CEleitorDinamico::CEleitorDinamico(const CEleitorIdentidade&, const CEleitorIdentidade&,
//         EEstadoComparecimento) as constructed in place by novos.emplace_back (see
//         u04-foreign-fragments.cpp)
//   2728  std::__tree<map<md::CComparecimentoMesarioPK, md::CComparecimentoMesario>>::destroy(node*)
//   2809  std::__tree<map<CNumeroInscricaoEleitoral, CJustificadorDetalhe>>::destroy(node*)
//   5723  `return m_dao->SelectAll();` (DAO vtable slot 8, m_dao at +4) - ICF-shared body of
//         comum::servico::CJustificadorServico::SelectAll (object at CJustificador +28) and
//         comum::servico::CComparecimentoMesarioServico::SelectAll (object at the mesários repository
//         +40); both called by the wrapper of 6734. Not a CDAORepositorio method.

}  // namespace comum
